//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:2.0.50727.3053
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Daliboris.Statistiky {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daliboris.cz/schemata/statistiky.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daliboris.cz/schemata/statistiky.xsd", IsNullable=false)]
    public partial class jevy {
        
        private j[] jField;
        
        private int pocetField;
        
        private string popisField;
        
        private string identifikatorField;
        
        private System.DateTime vytvorenoField;
        
        private string zdrojField;
        
        private string jazykField;
        
        private jevyTyp typField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("j")]
        public j[] j {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pocet {
            get {
                return this.pocetField;
            }
            set {
                this.pocetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string popis {
            get {
                return this.popisField;
            }
            set {
                this.popisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identifikator {
            get {
                return this.identifikatorField;
            }
            set {
                this.identifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime vytvoreno {
            get {
                return this.vytvorenoField;
            }
            set {
                this.vytvorenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string jazyk {
            get {
                return this.jazykField;
            }
            set {
                this.jazykField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public jevyTyp typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daliboris.cz/schemata/statistiky.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daliboris.cz/schemata/statistiky.xsd", IsNullable=false)]
    public partial class j {
        
        private object oField;
        
        private d[] detailyField;
        
        private lokace lokaceField;
        
        private string nField;
        
        private int pField;
        
        private string rField;
        
        /// <remarks/>
        public object o {
            get {
                return this.oField;
            }
            set {
                this.oField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("d", IsNullable=false)]
        public d[] detaily {
            get {
                return this.detailyField;
            }
            set {
                this.detailyField = value;
            }
        }
        
        /// <remarks/>
        public lokace lokace {
            get {
                return this.lokaceField;
            }
            set {
                this.lokaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daliboris.cz/schemata/statistiky.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daliboris.cz/schemata/statistiky.xsd", IsNullable=false)]
    public partial class d {
        
        private int pocetField;
        
        private string popisField;
        
        private string identifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pocet {
            get {
                return this.pocetField;
            }
            set {
                this.pocetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string popis {
            get {
                return this.popisField;
            }
            set {
                this.popisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identifikator {
            get {
                return this.identifikatorField;
            }
            set {
                this.identifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daliboris.cz/schemata/statistiky.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daliboris.cz/schemata/statistiky.xsd", IsNullable=false)]
    public partial class lokace {
        
        private lokaceL[] lField;
        
        private int pField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("l", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public lokaceL[] l {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daliboris.cz/schemata/statistiky.xsd")]
    public partial class lokaceL {
        
        private string lField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string l {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daliboris.cz/schemata/statistiky.xsd")]
    public enum jevyTyp {
        
        /// <remarks/>
        ostatni,

		/// <remarks/>
		useky,

        /// <remarks/>
        odstavce,
        
        /// <remarks/>
        slova,
        
        /// <remarks/>
        znaky,

		/// <remarks/>
		ngramy,

        /// <remarks/>
        tagy,
        
        /// <remarks/>
        atributy,
        
        /// <remarks/>
        hodnoty,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daliboris.cz/schemata/statistiky.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daliboris.cz/schemata/statistiky.xsd", IsNullable=false)]
    public partial class detaily {
        
        private d[] dField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("d")]
        public d[] d {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
            }
        }
    }
}
