name: .NET Framework

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
       ref: feature_refactor
    - uses: nuget/setup-nuget@v1
    - name: Nuget restore
      run: nuget restore $Env:GITHUB_WORKSPACE\Brus.sln
    - name: Build with dotnet
      run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Daliboris.Statistiky.UI.WPF\Daliboris.Statistiky.UI.WPF.csproj -p:Configuration=Release
